### ISSUE TITLE
[0.5pt] Find external API - group task 

### ISSUE THREAD

**Issue by KingsleyIbe** [KingsleyIbe/capstone-2#4]
- Link: https://github.com/KingsleyIbe/capstone-2/projects/2
- Project Authors: 2 people (@KingsleyIbe and @Mithi-code)

**Comment by elisha2kyakpo1** [comment]
Hi Coders, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a link to the Github project. You should submit a link to the repo Github project and not just your repo.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by bimbolabuari** [comment]
Hi Team, 

You have done a good job so far 🚀  

## Highlights 🎉 

- Link to your GitHub project
- Information about the number of people in your group
- Assign task to each member

There are some issues that you still need to work on to go to the next project but you are almost there! 🎉 
 


## Required Changes ♻️

> If your group includes two people - remove all cards with Student C in the title.
- For two team members, Student C tasks should be removed (Student C is required for three teammates)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

--------


_Reviewed by  @bimbolabuari_

**Comment by Lameck1** [comment]
Hi, team,

You've done well implementing your Kanban board 👏🏼. 

### Highlights:
- You've properly assigned yourselves tasks ✔️
- Task distribution is fair ✔️

You are now all set up to begin work on your project.

Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
